apiVersion: v1
kind: Service
metadata:
  name: esp-nav-api
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: esp-nav-api
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esp-nav-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: esp-nav-api
    spec:
      containers:
        # [START esp]
        - name: esp
          image: gcr.io/endpoints-release/endpoints-runtime:1
          args: [
            "--http_port", "8080",
            "--backend", "127.0.0.1:6789",
            "--service", "nav-api.endpoints.staging-217409.cloud.goog",
            "--version", "2019-02-20r0",
          ]
          # [END esp]
          ports:
            - containerPort: 8080
        - name: nav-api
          image: gcr.io/staging-217409/nav-api:latest
          ports:
            - containerPort: 6789